---
- name: Create directory inner structure
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
  - '{{ directory.data }}'
  - '{{ directory.data }}/postgresql'
  - '{{ directory.data }}/nextcloud'