---
# tasks file for stack-dev
- name: 'Adding dev=true label to dev nodes'
  docker_node:
    hostname: "{{ hostvars[item]['hostname']  }}"
    labels:
      dev: "true"
    labels_state: merge
  with_items: "{{ groups['dev'] }}"